"""
Author: Rayhan Biju
Version: 10/27/2021
Description: This file contains code to test the logic in the api/nps_api_functions.py file and achieves 100% code
coverage.
"""
from unittest import TestCase
from api.nps_api_functions import find_park_from_keyword, get_coordinates, get_park_profile, get_activities, get_parks, \
    get_tags, grab_webcam_metadata


class Test(TestCase):

    """
    Tests if the find_park_from_keyword function is logically correct by comparing expected assertions to the ones
    produced by the function itself.
    """
    def test_find_park_by_keyword(self):
        function_dict_as_str = str(find_park_from_keyword('hiking'))

        assert 'Acadia' in function_dict_as_str
        assert 'Antietam' in function_dict_as_str
        assert len(function_dict_as_str) > 0
        assert 'alka' in function_dict_as_str
        assert 'https://www.nps.gov/alka/index.htm' in function_dict_as_str

    """
    Tests if the get_coordinates function is logically correct by comparing valid coordinates with the ones generated
    from the function itself.
    """
    def test_get_coordinates(self):
        function_dict_as_str = str(get_coordinates('acad'))

        assert 'latitude' in function_dict_as_str
        assert 'longitude' in function_dict_as_str
        assert '44.409286' in function_dict_as_str
        assert '-68.247501' in function_dict_as_str

    """
    Tests if the get_park_profile function is logically correct by comparing valid values such as the park's full 
    name, URL's, or cities with the ones generated from the function itself.
    """
    def test_get_park_profile(self):

        function_dict_as_str = str(get_park_profile('acad'))
        assert 'Acadia National Park protects the natural beauty' in function_dict_as_str
        assert 'Acadia' in function_dict_as_str
        assert 'Acadia National Park' in function_dict_as_str
        assert '23' in function_dict_as_str
        assert 'http://www.nps.gov/acad/planyourvisit/directions.htm' in function_dict_as_str
        assert 'ME' in function_dict_as_str
        assert 'Bar Harbor' in function_dict_as_str
        assert 'https://www.nps.gov/common/uploads/structured_data/3C7B45AE-1DD8-B71B-0B7EE131C7DFC2F5.jpg' in \
               function_dict_as_str

    """
    Tests if the get_activities function is logically correct by comparing valid values such 'swimming' or 'skiing'
    with the ones generated from the get_activites function. 
    """
    def test_get_activities(self):
        activity_list = get_activities()
        assert len(activity_list) == 40
        assert 'Swimming' in activity_list
        assert 'Skiing' in activity_list
        assert 'Canyoneering' in activity_list

    """
    Tests if the get_parks function is logically correct by comparing valid park names with what is generated by the
    get_parks function. 
    """
    def test_get_parks(self):
        parks_list = get_parks()

        assert 'Acadia National Park' in str(parks_list)
        assert len(parks_list) > 0
        assert 'African American Civil War Memorial' in str(parks_list)

    """
    Tests if the get_tags function is logically correct by comparing valid tags with what is generated by the 
    get_tags function itself.
    """
    def test_get_tags(self):
        things_to_do = get_tags('yell')
        assert 'Yellowstone National Park' in things_to_do
        assert len(things_to_do) > 0
        assert 'trail' in things_to_do
        assert 'moderate hike' in things_to_do

    """
    Tests if the grab_webcam_metadata function is logically correct by making sure that the grab_webcam_metadata 
    function returns image URL's. 
    """
    def test_grab_webcam_metadatadata(self):
        web_cam_data = grab_webcam_metadata('acad')
        assert len(web_cam_data) > 0
        assert '.jpg' in str(web_cam_data)
        web_cam_data = grab_webcam_metadata('adam')
        assert len(web_cam_data) == 0
        assert '.jpg' not in str(web_cam_data)


